/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Pdf: typeof import('./src/components/Pdf.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Summary: typeof import('./src/components/Summary.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    TimelineMagazine: typeof import('./src/components/TimelineMagazine.vue')['default']
  }
}
